const API_STATES = {
  CANCELLED: 'CANCELLED',
  FAILED: 'FAILED',
  STARTED: 'STARTED',
  SUCCEEDED: 'SUCCEEDED',
};

export const createApiStateConstant = CONSTANT => ({
  CONSTANT,
  CANCELLED: `${CONSTANT}/${API_STATES.CANCELLED}`,
  FAILED: `${CONSTANT}/${API_STATES.FAILED}`,
  STARTED: `${CONSTANT}/${API_STATES.STARTED}`,
  SUCCEEDED: `${CONSTANT}/${API_STATES.SUCCEEDED}`,
});
